# /tmp/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed
processors:
  batch:
  tail_sampling:
    decision_wait: 2s
    num_traces: 10000
    expected_new_traces_per_sec: 10
    decision_cache:
      sampled_cache_size: 100000
    policies:
      [
        {
          name: test-policy-5,
          type: status_code,
          status_code: { status_codes: [ERROR] },
        },
      ]
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch, tail_sampling]
    metrics:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
